"""
build_html.py
=============
Post-build utility that patches the Streamlit app URL into the HTML landing pages
(index.html and how_it_works.html) so their CTA buttons link directly to the
live Streamlit deployment.

Usage:
    python build_html.py --url https://yourapp.streamlit.app

Or with environment variable:
    STREAMLIT_URL=https://yourapp.streamlit.app python build_html.py

If no URL is provided, a localhost URL is used for local development.
"""

import argparse
import os
import re
from pathlib import Path

# ─────────────────────────────────────────────────────────
# Config
# ─────────────────────────────────────────────────────────
HTML_FILES = ["index.html", "how_it_works.html"]
PLACEHOLDER = "http://localhost:8501"

def patch_html(filepath: str, app_url: str) -> bool:
    """
    Replace all occurrences of the placeholder Streamlit URL in an HTML file
    with the real deployment URL.

    Returns True if the file was modified, False if no changes were needed.
    """
    path = Path(filepath)
    if not path.exists():
        print(f"  ⚠  Skipped (not found): {filepath}")
        return False

    content = path.read_text(encoding="utf-8")
    new_content = content.replace(PLACEHOLDER, app_url.rstrip("/"))

    if new_content == content:
        print(f"  ─  No changes needed: {filepath}")
        return False

    path.write_text(new_content, encoding="utf-8")
    count = content.count(PLACEHOLDER)
    print(f"  ✔  Patched {count} URL(s) in: {filepath}")
    return True


def inject_streamlit_nav(filepath: str, app_url: str) -> None:
    """
    Ensure the Streamlit app CTA button in nav is pointing to the correct URL.
    Targets buttons with text 'Start Check →' and similar patterns.
    """
    path = Path(filepath)
    if not path.exists():
        return

    content = path.read_text(encoding="utf-8")

    # Patch onclick handlers that reference streamlit
    updated = re.sub(
        r"(href=['\"])http://localhost:8501(['\"])",
        rf"\g<1>{app_url.rstrip('/')}\g<2>",
        content
    )

    if updated != content:
        path.write_text(updated, encoding="utf-8")
        print(f"  ✔  Injected nav URL in: {filepath}")


def write_env_js(app_url: str) -> None:
    """
    Write a tiny env.js snippet that exposes the Streamlit URL to any
    inline JavaScript in the HTML files.
    """
    env_path = Path("env.js")
    env_path.write_text(
        f"// Auto-generated by build_html.py — do not edit manually\n"
        f"window.DIAGNO_APP_URL = '{app_url.rstrip('/')}';\n",
        encoding="utf-8"
    )
    print(f"  ✔  Written: env.js  (DIAGNO_APP_URL = '{app_url}')")


def main():
    parser = argparse.ArgumentParser(
        description="Patch Streamlit deployment URL into DiagnoX HTML pages."
    )
    parser.add_argument(
        "--url",
        default=os.environ.get("STREAMLIT_URL", PLACEHOLDER),
        help="The live Streamlit app URL (e.g. https://yourapp.streamlit.app)"
    )
    parser.add_argument(
        "--no-env-js",
        action="store_true",
        help="Skip writing env.js"
    )
    args = parser.parse_args()

    app_url = args.url.rstrip("/")
    print(f"\n{'='*55}")
    print(f"  build_html.py — DiagnoX HTML Patcher")
    print(f"{'='*55}")
    print(f"  Target URL : {app_url}")
    print(f"  Files      : {', '.join(HTML_FILES)}")
    print(f"{'='*55}\n")

    changed = 0
    for html_file in HTML_FILES:
        if patch_html(html_file, app_url):
            changed += 1
        inject_streamlit_nav(html_file, app_url)

    if not args.no_env_js:
        write_env_js(app_url)

    print(f"\n  {'✅' if changed > 0 else 'ℹ️ '}  Done — {changed} file(s) updated.")
    print(f"  Open index.html in a browser to preview the landing page.\n")


if __name__ == "__main__":
    main()